name: book_search_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  multiple_result: ^1.0.4
  hive_flutter: ^1.1.0
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
